---
title: "about"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```

## Read in and clean files 

```{r}
both_sexes <- read.csv("both_sexes.csv")
head(both_sexes)
glimpse(both_sexes)

both_sexes_reduced <- both_sexes %>%
  select(year, HS_2534, SC_2534, BAp_2534, HS_3544, SC_3544, BAp_3544) %>%
  pivot_longer(!year, names_to = "education", values_to = "rate") %>% 
  separate(education, c('education', 'age')) %>%
  mutate(rate = 1-rate) %>%
  group_by(education, age) %>% 
  arrange(education, year) %>%
  mutate(change_b = rate - first(rate)) %>%
  ungroup()

both_sexes_reduced$education <- case_when(
  both_sexes_reduced$education == "SC" ~ "Some college",
  both_sexes_reduced$education == "HS" ~ "High school or less",
  T ~ 'College graduates')
both_sexes_reduced$education <- factor(both_sexes_reduced$education, 
                                       levels = c("High school or less", "Some college", "College graduates"))

both_sexes_reduced$age <- case_when(
  both_sexes_reduced$age == "2534" ~ "Ages 25-34",
  T ~ "Ages 35-44")

both_sexes_reduced$age <- factor(
  both_sexes_reduced$age, levels = c("Ages 25-34", "Ages 35-44"))  
```

## Create plot for portion of people who have never gotten married
```{r}
age25_34 <- both_sexes_reduced %>% filter(age == "Ages 25-34") %>% mutate(rate = 1-rate)
not_mar_plot <- ggplot(age25_34,
                        aes(x = year,
                            y = rate,
                            color = education)) +
  geom_line() +
  labs(y = "Portion",
       x = "Year",
       color = "Education") +
  ggtitle("Portion of People who have never been Married Ages 25-34") +
  theme_minimal() +
  theme(axis.title = element_text(),
        panel.grid.major = element_blank()) + 
  scale_color_brewer(palette = "Purples")
not_mar_plot
```



# Create plot for marriage rate baseline change
```{r}
mar_rate_plot <- ggplot(both_sexes_reduced,
                        aes(x = year,
                            y = change_b,
                            color = education)) +
  geom_line() +
  facet_wrap(vars(age)) +
  labs(y = "Change in Marriage Rate",
       x = "Year",
       color = "Education") +
  ggtitle("Marriage Rate Change since 1960") +
  theme_minimal() +
  theme(axis.title = element_text(),
        panel.grid.major = element_blank()) +
  scale_color_brewer(palette = 'Reds') 
mar_rate_plot
```
